language: python
notifications:
    slack: pydriller:GY8wzJPkOMy22cPAH7umESp9
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - unzip test-repos.zip
  - cd test-repos
  - git clone https://github.com/apache/hadoop.git
  - cd ..
install:
  - pip install -r test-requirements.txt
  - pip install codecov pytest-cov
script:
  - travis_wait 30 pytest -v --cov=pydriller/
after_success:
  - codecov